// Whole-project economics. Land is an economic cost even when contributed in kind.
export const DEFAULTS=Object.freeze({price92:275000,price100:290000,price106:305000,rate:1450,road:167100,privateWorks:200000,amenities:90000,fees:8,contingency:12,finance:200000,land:1200000,selling:3,other:0});
export const LABELS={price92:'The Nest · each of 8 homes (€)',price100:'The Garden · each of 6 homes (€)',price106:'The Grove · each of 8 homes (€)',rate:'Building cost / gross m² (€)',road:'Road completion (€)',privateWorks:'Private site works (€)',amenities:'Pool & wellness fit-out (€)',fees:'Professional fees (% of hard costs)',contingency:'Contingency (% of hard costs)',finance:'Finance allowance (€)',land:'Land opportunity cost (€)',selling:'Selling costs (% of revenue)',other:'Other / unrecoverable VAT (€)'};
export function inputs(raw={}){const out={};for(const[k,v]of Object.entries(DEFAULTS)){const n=raw[k]===undefined?v:Number(raw[k]);out[k]=Number.isFinite(n)?Math.max(0,Math.min(['selling','fees','contingency'].includes(k)?(k==='selling'?95:100):1e9,n)):v;}return out;}
export function calculate(raw={}){const x=inputs(raw),revenue=x.price92*8+x.price100*6+x.price106*8,construction=2216*x.rate,hard=construction+x.road+x.privateWorks+x.amenities,fees=hard*x.fees/100,contingency=hard*x.contingency/100,selling=revenue*x.selling/100,development=hard+fees+contingency+x.finance+x.other,cost=development+x.land+selling,profit=revenue-cost,breakeven=(development+x.land)/(1-x.selling/100),margin=revenue?profit/revenue:0;
 const costMultiplier=1+(x.fees+x.contingency)/100,rateFor15=(revenue*(1-x.selling/100-.15)-x.finance-x.other-x.land-(x.road+x.privateWorks+x.amenities)*costMultiplier)/(2216*costMultiplier);
 return{x,revenue,construction,hard,fees,contingency,selling,development,cost,profit,margin,breakeven,averagePrice:revenue/22,breakEvenPerHome:breakeven/22,rateFor15,cashCost:cost-x.land,returnOnCost:cost?profit/cost:0};}
export function sensitivity(raw={}){const x=inputs(raw);return[{label:'Base assumptions',result:calculate(x)},{label:'Selling prices 10% lower',result:calculate({...x,price92:x.price92*.9,price100:x.price100*.9,price106:x.price106*.9})},{label:'Building cost 10% higher',result:calculate({...x,rate:x.rate*1.1})},{label:'Both pressures together',result:calculate({...x,rate:x.rate*1.1,price92:x.price92*.9,price100:x.price100*.9,price106:x.price106*.9})}];}
// Rough like-for-like commercial screens, not surveyed architectural alternatives.
export function screens(){return[{name:'16 detached homes',count:16,revenue:6400000,rate:1600,extra:0,note:'€400k average sale; €1,600/m² build target. More separate envelopes and services.'},{name:'20 larger townhouses',count:20,revenue:6300000,rate:1450,extra:0,note:'€315k average sale; same overall floor budget and build target.'},{name:'22 courtyard homes',count:22,revenue:6380000,rate:1450,extra:0,note:'Selected mix: 8 × €275k, 6 × €290k, 8 × €305k. Fully dimensioned concept.'},{name:'24 garden apartments',count:24,revenue:6280000,rate:1450,extra:180000,note:'8 one-bed at €205k; 8 two-bed at €275k; 8 larger two-bed at €305k. €180k provisional six-lift allowance.'}].map(s=>{const hard=2216*s.rate+DEFAULTS.road+DEFAULTS.privateWorks+DEFAULTS.amenities+s.extra,cost=hard*1.2+DEFAULTS.finance+DEFAULTS.land+s.revenue*.03;return {...s,cost,profit:s.revenue-cost};});}
